config/routes.rb
Rails.application.routes.draw do


  get 'shopping_carts/show'

  get "/carrito", to: "shopping_carts#show"
  get "/confirm", to: "service_orders#index"
  get "/add/:product_id", as: :add_to_cart, to:"in_shopping_carts#create"
  get "/delete/:id", as: :delete_to_cart, to:"in_shopping_carts#destroy"
  get "/checkout", to: "payments#checkout"
  get "/ok", to: "welcome#payment_succes"
  get "/who", to: "info#who"
 



  resources :products
  resources :in_shopping_carts, only: [:create, :destroy]
  resources :images, only: [:create, :destroy, :new]
  resources :service_orders, only: [:create,:new]

  devise_for :users

  post "/emails/create", as: :create_email
  post "pay", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"
  
  
  authenticated :user do  
  	root 'products#index'
  end



  unauthenticated :user do
   	devise_scope :user do 
  		root "welcome#unregistered", as: :unregistered_root
  	end	
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contac_email.rb
# == Schema Information
#
# Table name: contac_emails
#
#  id         :integer          not null, primary key
#  email      :string
#  ip         :string
#  state      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ContacEmail < ApplicationRecord
	validates_presence_of :email
	validates_uniqueness_of :email
	validates_format_of :email, with: Devise::email_regexp
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                 :integer          not null, primary key
#  product_id         :integer
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Image < ApplicationRecord
	belongs_to :product
	validates :image, attachment_presence: true

	has_attached_file :image, styles: { medium:"300x400", thumb:"100x100"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/in_shopping_cart.rb
# == Schema Information
#
# Table name: in_shopping_carts
#
#  id               :integer          not null, primary key
#  product_id       :integer
#  shopping_cart_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class InShoppingCart < ApplicationRecord
  belongs_to :product
  belongs_to :shopping_cart
  has_one :user, through: :product
end

app/models/my_payment.rb
# == Schema Information
#
# Table name: my_payments
#
#  id               :integer          not null, primary key
#  email            :string
#  ip               :string
#  status           :string
#  fee              :decimal(6, 2)
#  paypal_id        :string
#  total            :decimal(10, 2)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  shopping_cart_id :integer
#

class MyPayment < ApplicationRecord
belongs_to :shopping_cart

include AASM
	aasm column: "status" do 
		state :created, initial: true
		state :payed
		state :failed

		event :pay do
			after do
				shopping_cart.pay!
			end
			transitions from: :created, to: :payed
		end
	end

	def method_name
		
	end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  pricing             :integer
#  description         :text
#  user_id             :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  image1              :attachment
#  image2              :attachment
#  content             :text
#

class Product < ApplicationRecord
  belongs_to :user
  has_many :images
  validates_presence_of :name,:user,:pricing
  validates :pricing, numericality: {greater_than: 0}

  has_attached_file :avatar, styles: { medium:"300x400", thumb:"100x100"}, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  def paypal_form
  	{name: name, sku: :item, price: pricing ,currency:"USD", quantity: 1}
  	
  end

end

app/models/service_order.rb
# == Schema Information
#
# Table name: service_orders
#
#  id               :integer          not null, primary key
#  para             :string
#  de               :string
#  telefono         :string
#  date             :date
#  email            :string
#  hora             :string
#  direccion        :string
#  shopping_cart_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#


class ServiceOrder < ApplicationRecord
	
	belongs_to :shopping_cart
	after_create :send_email
	has_many :products, through: :shopping_cart

private
	def send_email
		OrderMailer.download_order(self).deliver_now
		
	end

end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  id         :integer          not null, primary key
#  status     :string
#  ip         :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShoppingCart < ApplicationRecord

	include AASM
 	has_many :service_order
	has_many :products, through: :in_shopping_carts
	has_many :in_shopping_carts

	aasm column: "status" do 
		state :created, initial: true
		state :payed
		state :failed

		event :pay do
			after do
				#shopping_cart.pay!
			end
			transitions from: :created, to: :payed
		end
	end

	def items
		self.products.map{|product| product.paypal_form}
		
	end

	def total
		products.sum(:pricing)
		
	end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
  	@email = ContacEmail.new(email: params[:email])
  		if @email.save
  			render json: @email
  		else
  			render json: @email.errors, status: :unprocessable_entity
  		end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
   
  before_action :authenticate_user!
  before_action :set_image, only:[:destroy]
  before_action :set_product, only:[:destroy]
  before_action :authenticate_owner!


  def show
  	
  end

  def new
  end  

  def create
  	@image = Image.new(image_params)
  	if @image.save
  		redirect_to @image.product, notice: "Se guardo la imagen con exito"
  	else
  		redirect_to @product, alert: "No se pudo guardar la imagen "
  	end
  end

  def destroy
    @image.destroy
    redirect_to @product
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def set_product
      @product = @image.product
    end

  	def authenticate_owner!

      if params.has_key? :image
  		  @product = Product.find(params[:image][:product_id])
      end

  		if @product.user != current_user || @product.nil? 
  			redirect_to root_path, notice: "No puedes editar este producto"
  			return
  		end
  	end

  def image_params
  	params.require(:image).permit(:product_id,:image)
  	
  end

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def who
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/service_orders_helper.rb
module ServiceOrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROYAL GIFT</title>

     <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css" type="text/css" >
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/nav" %>  
    <div style="<%= "display:none" if notice.nil? %>" class="no-margin no-padding">
      <p class="alert alert-info no-padding no-margin"><%= notice %></p>
    </div> 
    <div style="<%= "display:none" if alert.nil? %>" class="no-margin no-padding">
      <p class="alert alert-info no-padding no-danger"><%= alert %></p>
    </div>    
    <div class="col-lg-12 no-padding">
      <%= yield %>
    </div>
    <div class="col-lg-12"></div>
    <div class="row bottom-xs light-blue large-padding">
      <div class="col-xs-12">
        <div class="box">
             <footer class="other-grey-text">
               <div class="border-bottom">
                 Siguenos en facebook
               </div>
               <div class="col-lg-6 ">
                 <a href="who"class="block">¿Quienes somos?</a>
                 <span class="block">Politicas de calidad</span>
                 <span class="block">Acerca de nuestras formas de pago</span>
               </div>
               <div class="col-lg-6 ">
                 <span class="block">royalgiftbogota@gmail.com</span>
                 <span class="block">Telefonos: 5386524/3197370611</span>
                 
               </div>
             </footer>
        </div>
    </div>
</div>
  </body>
</html>

app/views/partials/_nav.haml
%header.no-margin
	%nav.turkey
		%ul.no-list.text-center.no-margin.bold.no-padding
			%li.col-md-2.inline-block.text-center.no-padding
				=image_tag "corona.png", height:"25px"
				=image_tag "logo.png", height:"25px"
			%li.col-md-6.inline-block.tall-padding
				-if user_signed_in?
					=link_to new_product_path, class: "right-space no-decoration" do
						%i.mdi-action-shopping-basket.gold-text
						+ Producto
					=link_to root_path, class: "right-space no-decoration" do
						%i.mdi-action-trending-up.gold-text
						Ordenes
					=link_to root_path, class: "right-space no-decoration" do
						%i.mdi-action-alarm.gold-text
						Descuentos
					=link_to destroy_user_session_path, method: :delete do
						Cerrar sesion
				-else
					=link_to root_path, class: "center-space josefin no-decoration" do
						HOME
					=link_to products_path, class: "center-space josefin no-decoration" do
						PRODUCTOS
					=link_to root_path, class: "center-space josefin no-decoration" do
						DESAYUNOS EMPRESARIALES
					=link_to root_path, class: "center-space josefin no-decoration" do
						CONTACTO
			%li.col-md-4.inline-block.tall-padding
				=link_to carrito_path, class:"white-text no-decoration josefin" do
					%div
						%span.white-text.center-xs
							MI CARRITO
						%i.mdi-action-shopping-cart
						(
						%span.other-grey-text= @shopping_cart.products.count
						)