config/routes.rb
Rails.application.routes.draw do


  get 'shopping_carts/show'

  get "/carrito", to: "shopping_carts#show"
  get "/confirm", to: "service_orders#index"
  get "/add/:product_id", as: :add_to_cart, to:"in_shopping_carts#create"
  get "/delete/:id", as: :delete_to_cart, to:"in_shopping_carts#destroy"
  get "/checkout", to: "payments#checkout"
  get "/ok", to: "welcome#payment_succes"
  get "/who", to: "info#who"
 



  resources :products
  resources :in_shopping_carts, only: [:create, :destroy]
  resources :images, only: [:create, :destroy, :new]
  resources :service_orders, only: [:create,:new]

  devise_for :users

  post "/emails/create", as: :create_email
  post "pay", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"
  
  
  authenticated :user do  
  	root 'products#index'
  end



  unauthenticated :user do
   	devise_scope :user do 
  		root "welcome#unregistered", as: :unregistered_root
  	end	
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  pricing             :integer
#  description         :text
#  user_id             :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  image1              :attachment
#  image2              :attachment
#  content             :text
#

class Product < ApplicationRecord
  belongs_to :user
  has_many :images
  validates_presence_of :name,:user,:pricing
  validates :pricing, numericality: {greater_than: 0}

  has_attached_file :avatar, styles: { medium:"300x400", thumb:"100x100"}, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  def paypal_form
  	{name: name, sku: :item, price: pricing ,currency:"USD", quantity: 1}
  	
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if user_signed_in? && current_user == @product.user && !params.key?(:client)
      @image = Image.new 
      render :admin
      
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :pricing, :description, :avatar, :content)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.haml
= form_for @product, builder: BootstrapFormBuilder do |f|
  = f.errors
  = f.text_field :name
  = f.text_field :pricing
  = f.text_area :description
  = f.text_area :content
  = f.file_field :avatar
  = f.submit :Crear

app/views/products/admin.haml
.col-md-3.inline-block.in-top
	%nav.medium
		.grey-text.light-green.col-md-12.large-padding
			Administracion
.col-md-9.inline-block.in-top
	.card.large-padding
		.col-md-9.inline-block
			%h1= @product.name
		.col-md-3.inline-block
			%p.big.no-margin.red-text= @product.pricing
		%nav.top-space.grey
			=link_to product_path(id: @product.id, client: true), class:"grey large-padding text-center col-md-4 inline-block" do
				Ver como cliente
			=link_to edit_product_path(@product), class:"grey large-padding text-center col-md-4 inline-block" do
				Editar producto
			=link_to @product, method: :delete, class:"grey large-padding text-center col-md-4 inline-block", data: { confirm: "Estas seguro de eliminar el producto"} do
				Eliminar
		%div
			%h3.grey-text Subir imagenes
			=render "images/form", product_id: @product.id
			%ol
				-@product.images.each do |i|
					%li.large-margin.grey-text.other-grey
						.col-xs-11.inline-block= i.image_file_name
						.col-xs-1.inline-block
							=link_to i, method: :delete,:"data-confirm"=>"Estas seguro que quieres borrar esta imagen?", class:"red-text" do
								%i.mdi-action-delete

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.haml
.top-space
.col-lg-12.container-owner.big-padding
  .col-lg-9.middle-xs.bold.normal.relative.grey-text
    Regala hoy un detalle unico y especial para pasar un dia espectacular con Royal Gift
  .col-lg-3.grey-text
    %p.no-margin.text-left Tel 5386524 / 3118901557
    %p.no-margin.text-left royalgiftbogota@gmail.com
    %p.no-margin.text-left Bogota/Colombia
.col-lg-2.grey-text.no-margin
  .top-space
    %span.block.bold ZONAS DE COVERTURA
    %span.block Segunda frase
    %span.block Tercera frase
  =image_tag("caja3.png", size: "120x120") 
  %P.no-padding.no-margin Estuche de lujo
  =image_tag("mesa.png", size: "120x120") 
  %P.no-padding.no-margin Estuche de lujo
  =image_tag("baul.png", size: "120x120") 
  %P.no-padding.no-margin Estuche de lujo
  =image_tag("picnic.png", size: "120x120") 
  %P.no-padding.no-margin Estuche de lujo
  =image_tag("jinjan.png", size: "120x120") 
  %P.no-padding.no-margin Estuche de lujo
.col-lg-10.no-margin.no-padding
  -@products.each do |p|  
    .col-md-3.no-padding-right.margin-top-little.inline-block
      %div{ id:"#{p.id}", onmouseover:"card('#{p.id}');", onmouseout:"normal('#{p.id}');"}
        =image_tag(p.avatar,class:"block", size:"280x200")
        .padding-little
          .bold.white-text.turkey.center.padding-little= p.name
          %p.black-text.no-margin
            %span.bold Precio $
            =p.pricing
          .orange.center.btn.btn-info.no-decoration
            =link_to 'Ver mas', p
          .bottom-space

app/views/products/new.haml
.col-md-8.col-xs-10.col-sm-11.no-float.center-block
	.card.large-padding
		%h1 Nuevo producto
		= render 'form', product: @product
		= link_to 'Back', products_path

app/views/products/show.haml
%div
	=link_to product_path, class:"black-text" do
		PRODUCTOS/
		=@product.name
.top-space
.col-lg-2.col-md-2.images
	%div.up.other-grey.center{ id:"up", onclick:"mover();"}
		%i.mdi-hardware-keyboard-arrow-up
	%div.center.hi{ id:"slider" }
		-n = 1
		=image_tag(@product.avatar, class:"center", size:"120x108", value:"#{n}", id:"#{n}", onmouseover:"loaderimage('#{n}');")
		-@product.images.each do |image|
			-n = n+1
			%section
				=image_tag(image.image, class:"center", size:"120x108", value:"#{n}", id:"#{n}", onmouseover:"loaderimage('#{n}');")
	%div.up.other-grey.center{ id:"down" }
		%i.mdi-hardware-keyboard-arrow-down
	
.col-lg-7.col-md-5.col-xs-12.col-sm-11.no.float.center-block.no-margin.no-padding
	%article.big-padding
		%div
			.col-xs-8.col-md-8.no-padding.inline-block.border-bottom.margin-bottom.no-margin-left
				=image_tag(@product.avatar, class:"block", size:"420x350", id:"bigimage")
			.col-xs-4.col-md-4.inline-block.text-left.absolute
				%h1.light-blue-text.amatic= @product.name
				.top-space
				%h3.bold.normal
					%span.red-text=" $#{@product.pricing} pesos"
				.top-space
					%span.grey-text.josefin
						%br=@product.description
				%div.center.inline-block.margin-botton
					=render "in_shopping_carts/form", product: @product
				.top-space
				=link_to 'https://www.facebook.com/royalgiftbogota/', :target => :blank, class:"btn btn-info" do
					=image_tag("facebook.png")
					ROYAL GIFT

		.top-space
.col-lg-3.col-md-3.no-padding.no-margin
	%article.big-padding
		%header.center.text-left
			%h5.grey-text.bold
				POLITICAS Y CONDICIONES
			%ul.text-left.no-margin-top.no-margin-right.margin-left-mini.josefin.no-padding
				%li
					El valor incluye el transporte dentro de la ciudad de bogota, para lugares aledaños porfavor contactarse para verificar excedente
				%li
					no se entrgan pedidos fuera de los horarion
				%li
					no se entrgan pedidos fuera de los horarion
				%li
					no se entrgan pedidos fuera de los horarion
.col-md-1.large-padding
.col-md-9.other-grey.large-padding
	%h4.bold
		CONTENIDO
	.text-left.no-margin-top.no-margin-left.josefin
		=@product.content
.top-space
	

app/views/products/slide.haml
.big-padding
	=form_tag(create_email_path, method: :post, remote: true, id:"emails-form") do
		=email_field_tag "email", nil,placeholder:"escribe aqui tu email"
	#email-info.big-padding
.col-md-12
	%div{:class => "carousel slide", :id => "carousel-1", "data-ride" =>"carousel"}
		%ol.carousel-indicators
			%li.active{"data-target"=>"#carousel-1", "data-slide-to"=>"0"}
			%li{"data-target"=>"#carousel-1", "data-slide-to"=>"1"}
			%li{"data-target"=>"#carousel-1", "data-slide-to"=>"2"}
		.carousel-inner{:role => "listbox"}
			.item.active
				.img-responsive
			.item
				.img-responsive
			.item
				.img-responsive